frameworkVersion: '2'

## These variables should be updates before running any of the serverless
## commands. The variables are used in the rest pf the template. If you want
## to see how they are resolved, run `serverless print`
custom:
  akkaServerlessProject: acme-sunglasses
  dockerUser: retgits
  dockerTag: '1.0.0'

service: ${self:custom.akkaServerlessProject}

provider:
  name: akkaserverless
  docker:
    imageUser: docker.io/${self:custom.dockerUser}

functions:
  orders:
    handler: dockerfile
    context: ./orders
    tag: ${self:custom.dockerTag}
    skipBuild: false
    proxyHostPort: 9001
  warehouse:
    handler: dockerfile
    context: ./warehouse
    tag: ${self:custom.dockerTag}
    skipBuild: false
    proxyHostPort: 9002
  users:
    handler: dockerfile
    context: ./users
    tag: ${self:custom.dockerTag}
    skipBuild: false
    proxyHostPort: 9003

plugins:
  - '@retgits/akkasls-serverless-framework'